module ResourceFiles

open ResourceFileMetadata

let GameFontResourceImages =
    [
        "MilitaryFontRed.png"    
        "MilitaryFontYellow.png" 
        "MilitaryFontBlue.png"   
        "MilitaryFontBlack.png"  
        "MilitaryFontSymbols.png"
    ]

let GameResourceImages =
    [|
        NoColourKey,      "CliffsTile.png"
        MagentaColourKey, "Title.png"

        NoColourKey,      "Map.png"
        MagentaColourKey, "AlliedFleetSymbol.png"
        MagentaColourKey, "EnemyFleetSymbol.png"

        NoColourKey,      "SecretPassage.png"
        MagentaColourKey, "Mine.png"
        MagentaColourKey, "Ship0.png"
        MagentaColourKey, "Ship1.png"
        MagentaColourKey, "Ship2.png"
        MagentaColourKey, "Ship3.png"
        MagentaColourKey, "Ship4.png"
        MagentaColourKey, "Torpedo0.png"
        MagentaColourKey, "Torpedo22degrees.png"
        MagentaColourKey, "ShipExplode0.png"
        MagentaColourKey, "ShipExplode1.png"
        MagentaColourKey, "ShipExplode2.png"
        MagentaColourKey, "ShipExplode3.png"

        MagentaColourKey, "Plane0.png"
        MagentaColourKey, "Plane1.png"
        MagentaColourKey, "Plane2.png"
        MagentaColourKey, "Plane3.png"
        MagentaColourKey, "Plane4.png"
        MagentaColourKey, "Plane4BankingLeft.png"
        MagentaColourKey, "Plane4BankingRight.png"
        MagentaColourKey, "Plane5.png"
        MagentaColourKey, "Plane5BankingLeft.png"
        MagentaColourKey, "Plane5BankingRight.png"
        MagentaColourKey, "Plane6.png"
        MagentaColourKey, "Plane6BankingLeft.png"
        MagentaColourKey, "Plane6BankingRight.png"
        MagentaColourKey, "PlaneExplode0.png"
        MagentaColourKey, "PlaneExplode1.png"
        MagentaColourKey, "PlaneExplode2.png"
        MagentaColourKey, "Splash0.png"
        MagentaColourKey, "PlaneBomb0.png"
        MagentaColourKey, "PlaneBomb1.png"
        MagentaColourKey, "PlaneBomb2.png"
        MagentaColourKey, "PlaneBomb3.png"
        MagentaColourKey, "PlaneBomb4.png"

        MagentaColourKey, "SeaBattleBackground0.png"
        MagentaColourKey, "SeaBattleBackground1.png"
        MagentaColourKey, "SeaBattleBackground2.png"
        MagentaColourKey, "SeaBattleBackground3.png"
        MagentaColourKey, "EnemyShip0.png"
        MagentaColourKey, "EnemyShip1.png"
        MagentaColourKey, "EnemyShip2.png"
        MagentaColourKey, "EnemyShip3.png"
        MagentaColourKey, "EnemyShip4.png"

        NoColourKey,      "TankBattleMissile.png"
        NoColourKey,      "TileBarricade.png"
        NoColourKey,      "TileBridge.png"
        NoColourKey,      "TileMine.png"
        NoColourKey,      "TileSand.png"
        NoColourKey,      "TileTower.png"
        NoColourKey,      "TileWater.png"
        MagentaColourKey, "EnemyTankGun1.png"
        MagentaColourKey, "TankFacingLeft0.png"
        MagentaColourKey, "TankFacingUpLeft0.png"
        MagentaColourKey, "TankFacingDownLeft0.png"
        MagentaColourKey, "TankFacingLeft1.png"
        MagentaColourKey, "TankFacingUpLeft1.png"
        MagentaColourKey, "TankFacingDownLeft1.png"

        NoColourKey,      "FinalBossBackground.png"
        MagentaColourKey, "FinalBoss0.png"
        MagentaColourKey, "FinalBoss1.png"
        MagentaColourKey, "FinalBoss2.png"
        MagentaColourKey, "FinalBoss3.png"
        MagentaColourKey, "FinalBoss4.png"
        MagentaColourKey, "FinalBoss5.png"
        MagentaColourKey, "FinalBossSurrender0.png"
        MagentaColourKey, "FinalBossSurrender1.png"
        MagentaColourKey, "FinalBossActiveTarget.png"
        MagentaColourKey, "FinalBossTarget.png"

        MagentaColourKey, "ShipGunNozzle.png"
        NoColourKey,      "ShipGunStem.png"
        MagentaColourKey, "ShipGunBullet.png"
        NoColourKey,      "IntermissionBackground.png"

        NoColourKey,      "VictoryScreen.png"
        MagentaColourKey, "ColonelReceivingMedal.png"
        MagentaColourKey, "ColonelSaluting.png"
        MagentaColourKey, "ColonelStanding.png"
        MagentaColourKey, "SoldierSaluting.png"
        MagentaColourKey, "SoldierStanding.png"
        MagentaColourKey, "Medal.png"
        MagentaColourKey, "PresidentPresentingMedal.png"
        MagentaColourKey, "PresidentSaluting.png"
        MagentaColourKey, "PresidentStanding.png"
    |]


